apiVersion: v1
kind: ConfigMap
metadata:
  name: taqueria
  namespace: taqueria
data:
  dt_metrics_endpoint: "https://rss61842.sprint.dynatracelabs.com/api/v2/otlp/v1/metrics"
  dt_traces_endpoint: "https://rss61842.sprint.dynatracelabs.com/api/v2/otlp/v1/traces"
---
apiVersion: v1
kind: Secret
metadata:
  name: taqueria
type: Opaque
stringData:
    dttoken: "(token here)"