apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: taqueria
  name: taqueria
rules:
- apiGroups: [""]
  resources: ["deployments","pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-robot
  namespace: taqueria
subjects:
- kind: ServiceAccount
  name: job-robot
  namespace: taqueria
roleRef:
  kind: Role
  name: job-robot 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
      annotations:
        oneagent.dynatrace.com/inject: "false"
    spec:
      containers:
        - name: scheduler
          image: mreider/taqueria-scheduler
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
      serviceAccountName: job-robot