
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
      annotations:
        oneagent.dynatrace.com/inject: "false"
    spec:
      containers:
        - name: checkout
          image: mreider/taqueria-checkout
          imagePullPolicy: Always
          ports:
            - containerPort: 5002
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.5"
          env:
            - name: app
              value: "k8s"
            - name: FLASK_ENV
              value: production
            - name: dt_token
              valueFrom:
                secretKeyRef:
                  name: taqueria
                  key: dttoken
            - name: dt_metrics_endpoint
              valueFrom:
                configMapKeyRef:
                  name: taqueria
                  key: dt_metrics_endpoint
            - name: dt_traces_endpoint
              valueFrom:
                configMapKeyRef:
                  name: taqueria
                  key: dt_traces_endpoint
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  selector:
    app: checkout
  ports:
    - protocol: "TCP"
      port: 5002
      targetPort: 5002